#include<stdio.h>
int main()
{
    long long int n,div,mul,i,x,y;
    int sum=0;
    while(scanf("%lld",&n)&&n!=0){
        mul=n;
        sum=0;
        div=1;
        x=1;
        y=1;
        for(i=0;div!=0||x!=0||y!=0;i++){
            div=mul%10;
            x=mul%7;
            y=mul%9;
            mul=mul/10;
            sum=sum+div;
        }
        if(sum<10){
            printf("%d\n",sum);
        }
        else{
            mul=sum;
            div=1;
            sum=0;
            x=1;
            y=1;
            for(i=0;div!=0||x!=0||y!=0;i++){
            div=mul%10;
            x=mul%7;
            y=mul%9;
            mul=mul/10;
            sum=sum+div;
        }
        if(sum<10){
            printf("%d\n",sum);
        }
        else{
            mul=sum;
            div=1;
            sum=0;
            x=1;
            y=1;
            for(i=0;div!=0||x!=0||y!=0;i++){
            div=mul%10;
            x=mul%7;
            y=mul%9;
            mul=mul/10;
            sum=sum+div;
        }
        if(sum<10){
        printf("%d\n",sum);
        }
        else{
            mul=sum;
            div=1;
            sum=0;
            x=1;
            y=1;
            for(i=0;div!=0||x!=0||y!=0;i++){
            div=mul%10;
            x=mul%7;
            y=mul%9;
            mul=mul/10;
            sum=sum+div;
        }
        if(sum<10){
        printf("%d\n",sum);
        }
        else{
            mul=sum;
            div=1;
            sum=0;
            x=1;
            y=1;
            for(i=0;div!=0||x!=0||y!=0;i++){
            div=mul%10;
            x=mul%7;
            y=mul%9;
            mul=mul/10;
            sum=sum+div;
        }
        printf("%d\n",sum);
        }
        }
    }
    }
    }
    return 0;
}
